
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Guild` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Guild
 * 
 */
export type GuildModel = runtime.Types.Result.DefaultSelection<Prisma.$GuildPayload>

export type AggregateGuild = {
  _count: GuildCountAggregateOutputType | null
  _avg: GuildAvgAggregateOutputType | null
  _sum: GuildSumAggregateOutputType | null
  _min: GuildMinAggregateOutputType | null
  _max: GuildMaxAggregateOutputType | null
}

export type GuildAvgAggregateOutputType = {
  id: number | null
}

export type GuildSumAggregateOutputType = {
  id: number | null
}

export type GuildMinAggregateOutputType = {
  id: number | null
  discordId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GuildMaxAggregateOutputType = {
  id: number | null
  discordId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GuildCountAggregateOutputType = {
  id: number
  discordId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type GuildAvgAggregateInputType = {
  id?: true | runtime.Types.Skip
}

export type GuildSumAggregateInputType = {
  id?: true | runtime.Types.Skip
}

export type GuildMinAggregateInputType = {
  id?: true | runtime.Types.Skip
  discordId?: true | runtime.Types.Skip
  createdAt?: true | runtime.Types.Skip
  updatedAt?: true | runtime.Types.Skip
}

export type GuildMaxAggregateInputType = {
  id?: true | runtime.Types.Skip
  discordId?: true | runtime.Types.Skip
  createdAt?: true | runtime.Types.Skip
  updatedAt?: true | runtime.Types.Skip
}

export type GuildCountAggregateInputType = {
  id?: true | runtime.Types.Skip
  discordId?: true | runtime.Types.Skip
  createdAt?: true | runtime.Types.Skip
  updatedAt?: true | runtime.Types.Skip
  _all?: true | runtime.Types.Skip
}

export type GuildAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Guild to aggregate.
   */
  where?: Prisma.GuildWhereInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Guilds to fetch.
   */
  orderBy?: Prisma.GuildOrderByWithRelationInput | Prisma.GuildOrderByWithRelationInput[] | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GuildWhereUniqueInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Guilds from the position of the cursor.
   */
  take?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Guilds.
   */
  skip?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Guilds
  **/
  _count?: true | GuildCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: GuildAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: GuildSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GuildMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GuildMaxAggregateInputType
}

export type GetGuildAggregateType<T extends GuildAggregateArgs> = {
      [P in keyof T & keyof AggregateGuild]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGuild[P]>
    : Prisma.GetScalarType<T[P], AggregateGuild[P]>
}




export type GuildGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GuildWhereInput | runtime.Types.Skip
  orderBy?: Prisma.GuildOrderByWithAggregationInput | Prisma.GuildOrderByWithAggregationInput[] | runtime.Types.Skip
  by: Prisma.GuildScalarFieldEnum[] | Prisma.GuildScalarFieldEnum
  having?: Prisma.GuildScalarWhereWithAggregatesInput | runtime.Types.Skip
  take?: number | runtime.Types.Skip
  skip?: number | runtime.Types.Skip
  _count?: GuildCountAggregateInputType | true
  _avg?: GuildAvgAggregateInputType
  _sum?: GuildSumAggregateInputType
  _min?: GuildMinAggregateInputType
  _max?: GuildMaxAggregateInputType
}

export type GuildGroupByOutputType = {
  id: number
  discordId: string
  createdAt: Date
  updatedAt: Date
  _count: GuildCountAggregateOutputType | null
  _avg: GuildAvgAggregateOutputType | null
  _sum: GuildSumAggregateOutputType | null
  _min: GuildMinAggregateOutputType | null
  _max: GuildMaxAggregateOutputType | null
}

export type GetGuildGroupByPayload<T extends GuildGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GuildGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GuildGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GuildGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GuildGroupByOutputType[P]>
      }
    >
  >



export type GuildWhereInput = {
  AND?: Prisma.GuildWhereInput | Prisma.GuildWhereInput[] | runtime.Types.Skip
  OR?: Prisma.GuildWhereInput[] | runtime.Types.Skip
  NOT?: Prisma.GuildWhereInput | Prisma.GuildWhereInput[] | runtime.Types.Skip
  id?: Prisma.IntFilter<"Guild"> | number | runtime.Types.Skip
  discordId?: Prisma.StringFilter<"Guild"> | string | runtime.Types.Skip
  createdAt?: Prisma.DateTimeFilter<"Guild"> | Date | string | runtime.Types.Skip
  updatedAt?: Prisma.DateTimeFilter<"Guild"> | Date | string | runtime.Types.Skip
  Roles?: Prisma.RoleListRelationFilter | runtime.Types.Skip
  Groups?: Prisma.GroupListRelationFilter | runtime.Types.Skip
}

export type GuildOrderByWithRelationInput = {
  id?: Prisma.SortOrder | runtime.Types.Skip
  discordId?: Prisma.SortOrder | runtime.Types.Skip
  createdAt?: Prisma.SortOrder | runtime.Types.Skip
  updatedAt?: Prisma.SortOrder | runtime.Types.Skip
  Roles?: Prisma.RoleOrderByRelationAggregateInput | runtime.Types.Skip
  Groups?: Prisma.GroupOrderByRelationAggregateInput | runtime.Types.Skip
}

export type GuildWhereUniqueInput = Prisma.AtLeast<{
  id?: number | runtime.Types.Skip
  discordId?: string | runtime.Types.Skip
  AND?: Prisma.GuildWhereInput | Prisma.GuildWhereInput[] | runtime.Types.Skip
  OR?: Prisma.GuildWhereInput[] | runtime.Types.Skip
  NOT?: Prisma.GuildWhereInput | Prisma.GuildWhereInput[] | runtime.Types.Skip
  createdAt?: Prisma.DateTimeFilter<"Guild"> | Date | string | runtime.Types.Skip
  updatedAt?: Prisma.DateTimeFilter<"Guild"> | Date | string | runtime.Types.Skip
  Roles?: Prisma.RoleListRelationFilter | runtime.Types.Skip
  Groups?: Prisma.GroupListRelationFilter | runtime.Types.Skip
}, "id" | "discordId">

export type GuildOrderByWithAggregationInput = {
  id?: Prisma.SortOrder | runtime.Types.Skip
  discordId?: Prisma.SortOrder | runtime.Types.Skip
  createdAt?: Prisma.SortOrder | runtime.Types.Skip
  updatedAt?: Prisma.SortOrder | runtime.Types.Skip
  _count?: Prisma.GuildCountOrderByAggregateInput | runtime.Types.Skip
  _avg?: Prisma.GuildAvgOrderByAggregateInput | runtime.Types.Skip
  _max?: Prisma.GuildMaxOrderByAggregateInput | runtime.Types.Skip
  _min?: Prisma.GuildMinOrderByAggregateInput | runtime.Types.Skip
  _sum?: Prisma.GuildSumOrderByAggregateInput | runtime.Types.Skip
}

export type GuildScalarWhereWithAggregatesInput = {
  AND?: Prisma.GuildScalarWhereWithAggregatesInput | Prisma.GuildScalarWhereWithAggregatesInput[] | runtime.Types.Skip
  OR?: Prisma.GuildScalarWhereWithAggregatesInput[] | runtime.Types.Skip
  NOT?: Prisma.GuildScalarWhereWithAggregatesInput | Prisma.GuildScalarWhereWithAggregatesInput[] | runtime.Types.Skip
  id?: Prisma.IntWithAggregatesFilter<"Guild"> | number | runtime.Types.Skip
  discordId?: Prisma.StringWithAggregatesFilter<"Guild"> | string | runtime.Types.Skip
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Guild"> | Date | string | runtime.Types.Skip
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Guild"> | Date | string | runtime.Types.Skip
}

export type GuildCreateInput = {
  discordId: string
  createdAt: Date | string
  updatedAt: Date | string
  Roles?: Prisma.RoleCreateNestedManyWithoutGuildInput | runtime.Types.Skip
  Groups?: Prisma.GroupCreateNestedManyWithoutGuildInput | runtime.Types.Skip
}

export type GuildUncheckedCreateInput = {
  id?: number | runtime.Types.Skip
  discordId: string
  createdAt: Date | string
  updatedAt: Date | string
  Roles?: Prisma.RoleUncheckedCreateNestedManyWithoutGuildInput | runtime.Types.Skip
  Groups?: Prisma.GroupUncheckedCreateNestedManyWithoutGuildInput | runtime.Types.Skip
}

export type GuildUpdateInput = {
  discordId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  Roles?: Prisma.RoleUpdateManyWithoutGuildNestedInput | runtime.Types.Skip
  Groups?: Prisma.GroupUpdateManyWithoutGuildNestedInput | runtime.Types.Skip
}

export type GuildUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number | runtime.Types.Skip
  discordId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  Roles?: Prisma.RoleUncheckedUpdateManyWithoutGuildNestedInput | runtime.Types.Skip
  Groups?: Prisma.GroupUncheckedUpdateManyWithoutGuildNestedInput | runtime.Types.Skip
}

export type GuildCreateManyInput = {
  id?: number | runtime.Types.Skip
  discordId: string
  createdAt: Date | string
  updatedAt: Date | string
}

export type GuildUpdateManyMutationInput = {
  discordId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
}

export type GuildUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number | runtime.Types.Skip
  discordId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
}

export type GuildScalarRelationFilter = {
  is?: Prisma.GuildWhereInput | runtime.Types.Skip
  isNot?: Prisma.GuildWhereInput | runtime.Types.Skip
}

export type GuildCountOrderByAggregateInput = {
  id?: Prisma.SortOrder | runtime.Types.Skip
  discordId?: Prisma.SortOrder | runtime.Types.Skip
  createdAt?: Prisma.SortOrder | runtime.Types.Skip
  updatedAt?: Prisma.SortOrder | runtime.Types.Skip
}

export type GuildAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder | runtime.Types.Skip
}

export type GuildMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder | runtime.Types.Skip
  discordId?: Prisma.SortOrder | runtime.Types.Skip
  createdAt?: Prisma.SortOrder | runtime.Types.Skip
  updatedAt?: Prisma.SortOrder | runtime.Types.Skip
}

export type GuildMinOrderByAggregateInput = {
  id?: Prisma.SortOrder | runtime.Types.Skip
  discordId?: Prisma.SortOrder | runtime.Types.Skip
  createdAt?: Prisma.SortOrder | runtime.Types.Skip
  updatedAt?: Prisma.SortOrder | runtime.Types.Skip
}

export type GuildSumOrderByAggregateInput = {
  id?: Prisma.SortOrder | runtime.Types.Skip
}

export type GuildCreateNestedOneWithoutGroupsInput = {
  create?: Prisma.XOR<Prisma.GuildCreateWithoutGroupsInput, Prisma.GuildUncheckedCreateWithoutGroupsInput> | runtime.Types.Skip
  connectOrCreate?: Prisma.GuildCreateOrConnectWithoutGroupsInput | runtime.Types.Skip
  connect?: Prisma.GuildWhereUniqueInput | runtime.Types.Skip
}

export type GuildUpdateOneRequiredWithoutGroupsNestedInput = {
  create?: Prisma.XOR<Prisma.GuildCreateWithoutGroupsInput, Prisma.GuildUncheckedCreateWithoutGroupsInput> | runtime.Types.Skip
  connectOrCreate?: Prisma.GuildCreateOrConnectWithoutGroupsInput | runtime.Types.Skip
  upsert?: Prisma.GuildUpsertWithoutGroupsInput | runtime.Types.Skip
  connect?: Prisma.GuildWhereUniqueInput | runtime.Types.Skip
  update?: Prisma.XOR<Prisma.XOR<Prisma.GuildUpdateToOneWithWhereWithoutGroupsInput, Prisma.GuildUpdateWithoutGroupsInput>, Prisma.GuildUncheckedUpdateWithoutGroupsInput> | runtime.Types.Skip
}

export type GuildCreateNestedOneWithoutRolesInput = {
  create?: Prisma.XOR<Prisma.GuildCreateWithoutRolesInput, Prisma.GuildUncheckedCreateWithoutRolesInput> | runtime.Types.Skip
  connectOrCreate?: Prisma.GuildCreateOrConnectWithoutRolesInput | runtime.Types.Skip
  connect?: Prisma.GuildWhereUniqueInput | runtime.Types.Skip
}

export type GuildUpdateOneRequiredWithoutRolesNestedInput = {
  create?: Prisma.XOR<Prisma.GuildCreateWithoutRolesInput, Prisma.GuildUncheckedCreateWithoutRolesInput> | runtime.Types.Skip
  connectOrCreate?: Prisma.GuildCreateOrConnectWithoutRolesInput | runtime.Types.Skip
  upsert?: Prisma.GuildUpsertWithoutRolesInput | runtime.Types.Skip
  connect?: Prisma.GuildWhereUniqueInput | runtime.Types.Skip
  update?: Prisma.XOR<Prisma.XOR<Prisma.GuildUpdateToOneWithWhereWithoutRolesInput, Prisma.GuildUpdateWithoutRolesInput>, Prisma.GuildUncheckedUpdateWithoutRolesInput> | runtime.Types.Skip
}

export type GuildCreateWithoutGroupsInput = {
  discordId: string
  createdAt: Date | string
  updatedAt: Date | string
  Roles?: Prisma.RoleCreateNestedManyWithoutGuildInput | runtime.Types.Skip
}

export type GuildUncheckedCreateWithoutGroupsInput = {
  id?: number | runtime.Types.Skip
  discordId: string
  createdAt: Date | string
  updatedAt: Date | string
  Roles?: Prisma.RoleUncheckedCreateNestedManyWithoutGuildInput | runtime.Types.Skip
}

export type GuildCreateOrConnectWithoutGroupsInput = {
  where: Prisma.GuildWhereUniqueInput
  create: Prisma.XOR<Prisma.GuildCreateWithoutGroupsInput, Prisma.GuildUncheckedCreateWithoutGroupsInput>
}

export type GuildUpsertWithoutGroupsInput = {
  update: Prisma.XOR<Prisma.GuildUpdateWithoutGroupsInput, Prisma.GuildUncheckedUpdateWithoutGroupsInput>
  create: Prisma.XOR<Prisma.GuildCreateWithoutGroupsInput, Prisma.GuildUncheckedCreateWithoutGroupsInput>
  where?: Prisma.GuildWhereInput | runtime.Types.Skip
}

export type GuildUpdateToOneWithWhereWithoutGroupsInput = {
  where?: Prisma.GuildWhereInput | runtime.Types.Skip
  data: Prisma.XOR<Prisma.GuildUpdateWithoutGroupsInput, Prisma.GuildUncheckedUpdateWithoutGroupsInput>
}

export type GuildUpdateWithoutGroupsInput = {
  discordId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  Roles?: Prisma.RoleUpdateManyWithoutGuildNestedInput | runtime.Types.Skip
}

export type GuildUncheckedUpdateWithoutGroupsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number | runtime.Types.Skip
  discordId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  Roles?: Prisma.RoleUncheckedUpdateManyWithoutGuildNestedInput | runtime.Types.Skip
}

export type GuildCreateWithoutRolesInput = {
  discordId: string
  createdAt: Date | string
  updatedAt: Date | string
  Groups?: Prisma.GroupCreateNestedManyWithoutGuildInput | runtime.Types.Skip
}

export type GuildUncheckedCreateWithoutRolesInput = {
  id?: number | runtime.Types.Skip
  discordId: string
  createdAt: Date | string
  updatedAt: Date | string
  Groups?: Prisma.GroupUncheckedCreateNestedManyWithoutGuildInput | runtime.Types.Skip
}

export type GuildCreateOrConnectWithoutRolesInput = {
  where: Prisma.GuildWhereUniqueInput
  create: Prisma.XOR<Prisma.GuildCreateWithoutRolesInput, Prisma.GuildUncheckedCreateWithoutRolesInput>
}

export type GuildUpsertWithoutRolesInput = {
  update: Prisma.XOR<Prisma.GuildUpdateWithoutRolesInput, Prisma.GuildUncheckedUpdateWithoutRolesInput>
  create: Prisma.XOR<Prisma.GuildCreateWithoutRolesInput, Prisma.GuildUncheckedCreateWithoutRolesInput>
  where?: Prisma.GuildWhereInput | runtime.Types.Skip
}

export type GuildUpdateToOneWithWhereWithoutRolesInput = {
  where?: Prisma.GuildWhereInput | runtime.Types.Skip
  data: Prisma.XOR<Prisma.GuildUpdateWithoutRolesInput, Prisma.GuildUncheckedUpdateWithoutRolesInput>
}

export type GuildUpdateWithoutRolesInput = {
  discordId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  Groups?: Prisma.GroupUpdateManyWithoutGuildNestedInput | runtime.Types.Skip
}

export type GuildUncheckedUpdateWithoutRolesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number | runtime.Types.Skip
  discordId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  Groups?: Prisma.GroupUncheckedUpdateManyWithoutGuildNestedInput | runtime.Types.Skip
}


/**
 * Count Type GuildCountOutputType
 */

export type GuildCountOutputType = {
  Roles: number
  Groups: number
}

export type GuildCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Roles?: boolean | GuildCountOutputTypeCountRolesArgs
  Groups?: boolean | GuildCountOutputTypeCountGroupsArgs
}

/**
 * GuildCountOutputType without action
 */
export type GuildCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildCountOutputType
   */
  select?: Prisma.GuildCountOutputTypeSelect<ExtArgs> | null
}

/**
 * GuildCountOutputType without action
 */
export type GuildCountOutputTypeCountRolesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RoleWhereInput | runtime.Types.Skip
}

/**
 * GuildCountOutputType without action
 */
export type GuildCountOutputTypeCountGroupsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GroupWhereInput | runtime.Types.Skip
}


export type GuildSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean | runtime.Types.Skip
  discordId?: boolean | runtime.Types.Skip
  createdAt?: boolean | runtime.Types.Skip
  updatedAt?: boolean | runtime.Types.Skip
  Roles?: boolean | Prisma.Guild$RolesArgs<ExtArgs> | runtime.Types.Skip
  Groups?: boolean | Prisma.Guild$GroupsArgs<ExtArgs> | runtime.Types.Skip
  _count?: boolean | Prisma.GuildCountOutputTypeDefaultArgs<ExtArgs> | runtime.Types.Skip
}, ExtArgs["result"]["guild"]>

export type GuildSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean | runtime.Types.Skip
  discordId?: boolean | runtime.Types.Skip
  createdAt?: boolean | runtime.Types.Skip
  updatedAt?: boolean | runtime.Types.Skip
}, ExtArgs["result"]["guild"]>

export type GuildSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean | runtime.Types.Skip
  discordId?: boolean | runtime.Types.Skip
  createdAt?: boolean | runtime.Types.Skip
  updatedAt?: boolean | runtime.Types.Skip
}, ExtArgs["result"]["guild"]>

export type GuildSelectScalar = {
  id?: boolean | runtime.Types.Skip
  discordId?: boolean | runtime.Types.Skip
  createdAt?: boolean | runtime.Types.Skip
  updatedAt?: boolean | runtime.Types.Skip
}

export type GuildOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "discordId" | "createdAt" | "updatedAt", ExtArgs["result"]["guild"], runtime.Types.Skip>
export type GuildInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Roles?: boolean | Prisma.Guild$RolesArgs<ExtArgs> | runtime.Types.Skip
  Groups?: boolean | Prisma.Guild$GroupsArgs<ExtArgs> | runtime.Types.Skip
  _count?: boolean | Prisma.GuildCountOutputTypeDefaultArgs<ExtArgs> | runtime.Types.Skip
}
export type GuildIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type GuildIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $GuildPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Guild"
  objects: {
    Roles: Prisma.$RolePayload<ExtArgs>[]
    Groups: Prisma.$GroupPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    discordId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["guild"]>
  composites: {}
}

export type GuildGetPayload<S extends boolean | null | undefined | GuildDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GuildPayload, S>

export type GuildCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GuildFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GuildCountAggregateInputType | true
  }

export interface GuildDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Guild'], meta: { name: 'Guild' } }
  /**
   * Find zero or one Guild that matches the filter.
   * @param {GuildFindUniqueArgs} args - Arguments to find a Guild
   * @example
   * // Get one Guild
   * const guild = await prisma.guild.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GuildFindUniqueArgs>(args: Prisma.SelectSubset<T, GuildFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GuildClient<runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Guild that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GuildFindUniqueOrThrowArgs} args - Arguments to find a Guild
   * @example
   * // Get one Guild
   * const guild = await prisma.guild.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GuildFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GuildFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GuildClient<runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Guild that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildFindFirstArgs} args - Arguments to find a Guild
   * @example
   * // Get one Guild
   * const guild = await prisma.guild.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GuildFindFirstArgs>(args?: Prisma.SelectSubset<T, GuildFindFirstArgs<ExtArgs>>): Prisma.Prisma__GuildClient<runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Guild that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildFindFirstOrThrowArgs} args - Arguments to find a Guild
   * @example
   * // Get one Guild
   * const guild = await prisma.guild.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GuildFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GuildFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GuildClient<runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Guilds that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Guilds
   * const guilds = await prisma.guild.findMany()
   * 
   * // Get first 10 Guilds
   * const guilds = await prisma.guild.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const guildWithIdOnly = await prisma.guild.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GuildFindManyArgs>(args?: Prisma.SelectSubset<T, GuildFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Guild.
   * @param {GuildCreateArgs} args - Arguments to create a Guild.
   * @example
   * // Create one Guild
   * const Guild = await prisma.guild.create({
   *   data: {
   *     // ... data to create a Guild
   *   }
   * })
   * 
   */
  create<T extends GuildCreateArgs>(args: Prisma.SelectSubset<T, GuildCreateArgs<ExtArgs>>): Prisma.Prisma__GuildClient<runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Guilds.
   * @param {GuildCreateManyArgs} args - Arguments to create many Guilds.
   * @example
   * // Create many Guilds
   * const guild = await prisma.guild.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GuildCreateManyArgs>(args?: Prisma.SelectSubset<T, GuildCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Guilds and returns the data saved in the database.
   * @param {GuildCreateManyAndReturnArgs} args - Arguments to create many Guilds.
   * @example
   * // Create many Guilds
   * const guild = await prisma.guild.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Guilds and only return the `id`
   * const guildWithIdOnly = await prisma.guild.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GuildCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GuildCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Guild.
   * @param {GuildDeleteArgs} args - Arguments to delete one Guild.
   * @example
   * // Delete one Guild
   * const Guild = await prisma.guild.delete({
   *   where: {
   *     // ... filter to delete one Guild
   *   }
   * })
   * 
   */
  delete<T extends GuildDeleteArgs>(args: Prisma.SelectSubset<T, GuildDeleteArgs<ExtArgs>>): Prisma.Prisma__GuildClient<runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Guild.
   * @param {GuildUpdateArgs} args - Arguments to update one Guild.
   * @example
   * // Update one Guild
   * const guild = await prisma.guild.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GuildUpdateArgs>(args: Prisma.SelectSubset<T, GuildUpdateArgs<ExtArgs>>): Prisma.Prisma__GuildClient<runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Guilds.
   * @param {GuildDeleteManyArgs} args - Arguments to filter Guilds to delete.
   * @example
   * // Delete a few Guilds
   * const { count } = await prisma.guild.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GuildDeleteManyArgs>(args?: Prisma.SelectSubset<T, GuildDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Guilds.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Guilds
   * const guild = await prisma.guild.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GuildUpdateManyArgs>(args: Prisma.SelectSubset<T, GuildUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Guilds and returns the data updated in the database.
   * @param {GuildUpdateManyAndReturnArgs} args - Arguments to update many Guilds.
   * @example
   * // Update many Guilds
   * const guild = await prisma.guild.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Guilds and only return the `id`
   * const guildWithIdOnly = await prisma.guild.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GuildUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GuildUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Guild.
   * @param {GuildUpsertArgs} args - Arguments to update or create a Guild.
   * @example
   * // Update or create a Guild
   * const guild = await prisma.guild.upsert({
   *   create: {
   *     // ... data to create a Guild
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Guild we want to update
   *   }
   * })
   */
  upsert<T extends GuildUpsertArgs>(args: Prisma.SelectSubset<T, GuildUpsertArgs<ExtArgs>>): Prisma.Prisma__GuildClient<runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Guilds.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildCountArgs} args - Arguments to filter Guilds to count.
   * @example
   * // Count the number of Guilds
   * const count = await prisma.guild.count({
   *   where: {
   *     // ... the filter for the Guilds we want to count
   *   }
   * })
  **/
  count<T extends GuildCountArgs>(
    args?: Prisma.Subset<T, GuildCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GuildCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Guild.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GuildAggregateArgs>(args: Prisma.Subset<T, GuildAggregateArgs>): Prisma.PrismaPromise<GetGuildAggregateType<T>>

  /**
   * Group by Guild.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GuildGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GuildGroupByArgs['orderBy'] }
      : { orderBy?: GuildGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GuildGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGuildGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Guild model
 */
readonly fields: GuildFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Guild.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GuildClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Roles<T extends Prisma.Guild$RolesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Guild$RolesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RolePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Groups<T extends Prisma.Guild$GroupsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Guild$GroupsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GroupPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Guild model
 */
export interface GuildFieldRefs {
  readonly id: Prisma.FieldRef<"Guild", 'Int'>
  readonly discordId: Prisma.FieldRef<"Guild", 'String'>
  readonly createdAt: Prisma.FieldRef<"Guild", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Guild", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Guild findUnique
 */
export type GuildFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guild
   */
  select?: Prisma.GuildSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guild
   */
  omit?: Prisma.GuildOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildInclude<ExtArgs> | null
  /**
   * Filter, which Guild to fetch.
   */
  where: Prisma.GuildWhereUniqueInput
}

/**
 * Guild findUniqueOrThrow
 */
export type GuildFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guild
   */
  select?: Prisma.GuildSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guild
   */
  omit?: Prisma.GuildOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildInclude<ExtArgs> | null
  /**
   * Filter, which Guild to fetch.
   */
  where: Prisma.GuildWhereUniqueInput
}

/**
 * Guild findFirst
 */
export type GuildFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guild
   */
  select?: Prisma.GuildSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guild
   */
  omit?: Prisma.GuildOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildInclude<ExtArgs> | null
  /**
   * Filter, which Guild to fetch.
   */
  where?: Prisma.GuildWhereInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Guilds to fetch.
   */
  orderBy?: Prisma.GuildOrderByWithRelationInput | Prisma.GuildOrderByWithRelationInput[] | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Guilds.
   */
  cursor?: Prisma.GuildWhereUniqueInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Guilds from the position of the cursor.
   */
  take?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Guilds.
   */
  skip?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Guilds.
   */
  distinct?: Prisma.GuildScalarFieldEnum | Prisma.GuildScalarFieldEnum[] | runtime.Types.Skip
}

/**
 * Guild findFirstOrThrow
 */
export type GuildFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guild
   */
  select?: Prisma.GuildSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guild
   */
  omit?: Prisma.GuildOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildInclude<ExtArgs> | null
  /**
   * Filter, which Guild to fetch.
   */
  where?: Prisma.GuildWhereInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Guilds to fetch.
   */
  orderBy?: Prisma.GuildOrderByWithRelationInput | Prisma.GuildOrderByWithRelationInput[] | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Guilds.
   */
  cursor?: Prisma.GuildWhereUniqueInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Guilds from the position of the cursor.
   */
  take?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Guilds.
   */
  skip?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Guilds.
   */
  distinct?: Prisma.GuildScalarFieldEnum | Prisma.GuildScalarFieldEnum[] | runtime.Types.Skip
}

/**
 * Guild findMany
 */
export type GuildFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guild
   */
  select?: Prisma.GuildSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guild
   */
  omit?: Prisma.GuildOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildInclude<ExtArgs> | null
  /**
   * Filter, which Guilds to fetch.
   */
  where?: Prisma.GuildWhereInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Guilds to fetch.
   */
  orderBy?: Prisma.GuildOrderByWithRelationInput | Prisma.GuildOrderByWithRelationInput[] | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Guilds.
   */
  cursor?: Prisma.GuildWhereUniqueInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Guilds from the position of the cursor.
   */
  take?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Guilds.
   */
  skip?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Guilds.
   */
  distinct?: Prisma.GuildScalarFieldEnum | Prisma.GuildScalarFieldEnum[] | runtime.Types.Skip
}

/**
 * Guild create
 */
export type GuildCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guild
   */
  select?: Prisma.GuildSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guild
   */
  omit?: Prisma.GuildOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildInclude<ExtArgs> | null
  /**
   * The data needed to create a Guild.
   */
  data: Prisma.XOR<Prisma.GuildCreateInput, Prisma.GuildUncheckedCreateInput>
}

/**
 * Guild createMany
 */
export type GuildCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Guilds.
   */
  data: Prisma.GuildCreateManyInput | Prisma.GuildCreateManyInput[]
  skipDuplicates?: boolean | runtime.Types.Skip
}

/**
 * Guild createManyAndReturn
 */
export type GuildCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guild
   */
  select?: Prisma.GuildSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Guild
   */
  omit?: Prisma.GuildOmit<ExtArgs> | null
  /**
   * The data used to create many Guilds.
   */
  data: Prisma.GuildCreateManyInput | Prisma.GuildCreateManyInput[]
  skipDuplicates?: boolean | runtime.Types.Skip
}

/**
 * Guild update
 */
export type GuildUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guild
   */
  select?: Prisma.GuildSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guild
   */
  omit?: Prisma.GuildOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildInclude<ExtArgs> | null
  /**
   * The data needed to update a Guild.
   */
  data: Prisma.XOR<Prisma.GuildUpdateInput, Prisma.GuildUncheckedUpdateInput>
  /**
   * Choose, which Guild to update.
   */
  where: Prisma.GuildWhereUniqueInput
}

/**
 * Guild updateMany
 */
export type GuildUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Guilds.
   */
  data: Prisma.XOR<Prisma.GuildUpdateManyMutationInput, Prisma.GuildUncheckedUpdateManyInput>
  /**
   * Filter which Guilds to update
   */
  where?: Prisma.GuildWhereInput | runtime.Types.Skip
  /**
   * Limit how many Guilds to update.
   */
  limit?: number | runtime.Types.Skip
}

/**
 * Guild updateManyAndReturn
 */
export type GuildUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guild
   */
  select?: Prisma.GuildSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Guild
   */
  omit?: Prisma.GuildOmit<ExtArgs> | null
  /**
   * The data used to update Guilds.
   */
  data: Prisma.XOR<Prisma.GuildUpdateManyMutationInput, Prisma.GuildUncheckedUpdateManyInput>
  /**
   * Filter which Guilds to update
   */
  where?: Prisma.GuildWhereInput | runtime.Types.Skip
  /**
   * Limit how many Guilds to update.
   */
  limit?: number | runtime.Types.Skip
}

/**
 * Guild upsert
 */
export type GuildUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guild
   */
  select?: Prisma.GuildSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guild
   */
  omit?: Prisma.GuildOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildInclude<ExtArgs> | null
  /**
   * The filter to search for the Guild to update in case it exists.
   */
  where: Prisma.GuildWhereUniqueInput
  /**
   * In case the Guild found by the `where` argument doesn't exist, create a new Guild with this data.
   */
  create: Prisma.XOR<Prisma.GuildCreateInput, Prisma.GuildUncheckedCreateInput>
  /**
   * In case the Guild was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GuildUpdateInput, Prisma.GuildUncheckedUpdateInput>
}

/**
 * Guild delete
 */
export type GuildDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guild
   */
  select?: Prisma.GuildSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guild
   */
  omit?: Prisma.GuildOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildInclude<ExtArgs> | null
  /**
   * Filter which Guild to delete.
   */
  where: Prisma.GuildWhereUniqueInput
}

/**
 * Guild deleteMany
 */
export type GuildDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Guilds to delete
   */
  where?: Prisma.GuildWhereInput | runtime.Types.Skip
  /**
   * Limit how many Guilds to delete.
   */
  limit?: number | runtime.Types.Skip
}

/**
 * Guild.Roles
 */
export type Guild$RolesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Role
   */
  select?: Prisma.RoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Role
   */
  omit?: Prisma.RoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoleInclude<ExtArgs> | null
  where?: Prisma.RoleWhereInput | runtime.Types.Skip
  orderBy?: Prisma.RoleOrderByWithRelationInput | Prisma.RoleOrderByWithRelationInput[] | runtime.Types.Skip
  cursor?: Prisma.RoleWhereUniqueInput | runtime.Types.Skip
  take?: number | runtime.Types.Skip
  skip?: number | runtime.Types.Skip
  distinct?: Prisma.RoleScalarFieldEnum | Prisma.RoleScalarFieldEnum[] | runtime.Types.Skip
}

/**
 * Guild.Groups
 */
export type Guild$GroupsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Group
   */
  select?: Prisma.GroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Group
   */
  omit?: Prisma.GroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GroupInclude<ExtArgs> | null
  where?: Prisma.GroupWhereInput | runtime.Types.Skip
  orderBy?: Prisma.GroupOrderByWithRelationInput | Prisma.GroupOrderByWithRelationInput[] | runtime.Types.Skip
  cursor?: Prisma.GroupWhereUniqueInput | runtime.Types.Skip
  take?: number | runtime.Types.Skip
  skip?: number | runtime.Types.Skip
  distinct?: Prisma.GroupScalarFieldEnum | Prisma.GroupScalarFieldEnum[] | runtime.Types.Skip
}

/**
 * Guild without action
 */
export type GuildDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guild
   */
  select?: Prisma.GuildSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guild
   */
  omit?: Prisma.GuildOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildInclude<ExtArgs> | null
}
